@startuml
'https://plantuml.com/sequence-diagram

class Ex42{
    -String[] names
    -BufferedReader read
    -int i

    +readUserInput()
}

class processData{
    -ArrayList<String> names
    -ArrayList<String> lastNames
    -ArrayList<String> firstNames
    -ArrayList<String> salary
    -int i
    -int j
    -String currentString
    -String currentLastName
    -String currentFirstName
    -String currentSalary
    -int longestLastName
    -int longestFirstName
    -int longestSalary
    -int longestValue
    -ArrayList<String> values
    -int longestLength

    +splitData(names)
    +sortIntoTable(lastNames, firstNames, salary)
    +findLongestValues(values)
    +addInSpaces(i, values, longestLength)
}

Ex42 -- processData

@enduml

