@startuml
'https://plantuml.com/sequence-diagram

class Ex42{
    - String[] names
    - BufferedReader read
    - List<String>[] listOfArrays
    - List<String> lastNames
    - List<String> firstNames
    - List<String> salaries
    - int longestLastName
    - int longestFirstName
    - int longestSalary

    + main()
    + readUserInput()
    + sortIntoTable(names)
}

class processData{
    - ArrayList<String> names
    - ArrayList<String> lastNames
    - ArrayList<String> firstNames
    - ArrayList<String> salaries
    - String currentString
    - String currentLastName
    - String currentFirstName
    - String currentSalary
    - int longestValue
    - int i
    - ArrayList<String> values
    - int longestLength

    + splitData(names)
    + findLongestValues(values)
    + addInSpaces(i, values, longestLength)
}

Ex42 -- processData

@enduml

